[package]
name = "scorched"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", features = ["dynamic_linking"] }
noise = "0.9.0"
rand = "0.8.5"
simple_moving_average = "1.0.2"
